### ISSUE TITLE
crash when killing running threads

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1164]
**Describe the bug**
Cancelling installation during the unpack stage attempts to destroy a thread which is still running resulting in crash.

**To Reproduce**
1. install distro with squashfs
2. cancel while unpacking the squashfs
3. crash

**Expected behavior**
No crash & umounting done.

**Screenshots and Logs**
```
Thread 1 (Thread 0x7ffff7fc0780 (LWP 5412)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff534b801 in __GI_abort () at abort.c:79
#2  0x00007ffff5d20e7b in qt_message_fatal (context=..., message=<synthetic pointer>...) at global/qlogging.cpp:1901
#3  QMessageLogger::fatal (this=this@entry=0x7fffffffde10, msg=msg@entry=0x7ffff60061e8 "QThread: Destroyed while thread is still running")
    at global/qlogging.cpp:887
#4  0x00007ffff5d4236d in QThread::~QThread (this=0x5555559f68e0, __in_chrg=<optimized out>) at thread/qthread.cpp:445
#5  0x00007ffff76f2489 in Calamares::JobThread::~JobThread (this=0x5555559f68e0, __in_chrg=<optimized out>)
    at ./src/libcalamares/JobQueue.cpp:128
#6  0x00007ffff5f4a9fb in QObjectPrivate::deleteChildren (this=this@entry=0x555555a11c50) at kernel/qobject.cpp:1995
#7  0x00007ffff5f544fb in QObject::~QObject (this=<optimized out>, __in_chrg=<optimized out>) at kernel/qobject.cpp:1021
#8  0x00007ffff76f25b9 in Calamares::JobQueue::~JobQueue (this=0x5555559aad20, __in_chrg=<optimized out>)
    at ./src/libcalamares/JobQueue.cpp:161
#9  0x00007ffff5f4a9fb in QObjectPrivate::deleteChildren (this=this@entry=0x5555558c0790) at kernel/qobject.cpp:1995
#10 0x00007ffff5f544fb in QObject::~QObject (this=<optimized out>, __in_chrg=<optimized out>) at kernel/qobject.cpp:1021
#11 0x00007ffff5f1f896 in QCoreApplication::~QCoreApplication (this=0x7fffffffe2f0, __in_chrg=<optimized out>)
    at kernel/qcoreapplication.cpp:894
#12 0x00007ffff677aa43 in QGuiApplication::~QGuiApplication() () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#13 0x00007ffff6fb1309 in QApplication::~QApplication() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x0000555555565a9d in CalamaresApplication::~CalamaresApplication (this=0x7fffffffe2f0, __in_chrg=<optimized out>)
    at ./src/calamares/CalamaresApplication.cpp:91
#15 0x0000555555563d14 in main (argc=<optimized out>, argv=<optimized out>) at ./src/calamares/main.cpp:85
```

**Comment by apachelogger** [comment]
In fact it appears this crash happens regardless of which part is currently running. Qt 5.12.0 FWIW
