### ISSUE TITLE
v3.1.4-21-gbe2338ff0 introduce SIGSEGV

### ISSUE THREAD

**Issue by agaida** [calamares/calamares#805]
#### Submission type

  - [X] Bug report

#### Describe the issue you encountered

ec86922839eae9794ccb95 - works as expected
be2338ff08b2ea9ae6e7fb81 - SIGSEGV

> console output
```
$ sudo LANG=C calamares
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
20:04:42 [1]: Calamares version: 3.1.4.20170916-git-master-9197873-dirty
20:04:42 [1]: Default font =====
Pixel size:    -1
Point size:    9
Point sizeF:   9
Font family:   "Sans Serif"
Metric height: 15
20:04:42 [1]: Font height: 15
20:04:42 [1]: Available languages: ("ar", "ast", "bg", "ca", "cs_CZ", "da", "de", "el", "en", "en_GB", "es_MX", "es", "eu", "fr", "he", "hr", "hu", "id", "is", "it_IT", "ja", "lt", "nl", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sv", "th", "tr_TR", "zh_CN", "zh_TW")
20:04:42 [1]: CalamaresApplication thread: 0x564ecfedcc20
20:04:42 [1]: Using log file: "/root/.cache/Calamares/Calamares/Calamares.log"
20:04:42 [1]: Using Calamares settings file at "/etc/calamares/settings.conf"
20:04:42 [1]: Using Calamares branding file at "/etc/calamares/branding/siduction/branding.desc"
20:04:42 [1]: WARNING: the selected branding component does not ship translations.
20:04:42 [1]: Loaded branding component "siduction"
20:04:43 [1]: STARTUP: initQmlPath, initSettings, initBranding done
20:04:43 [1]: STARTUP: initModuleManager: module init started
20:04:43 [1]: STARTUP: initModuleManager: all modules init done
20:04:43 [1]: STARTUP: initJobQueue done
20:04:43 [1]: Available size QSize(1688, 1018)
20:04:43 [1]:   Proposed window size: 1024 540
20:04:43 [1]: STARTUP: CalamaresWindow created; loadModules started
Speicherzugriffsfehler
```
> gdb
```
Reading symbols from calamares...Reading symbols from /usr/lib/debug/.build-id/bb/08c13b7283403241818e72726fd8a1f0b5a260.debug...done.
done.
(gdb) start
Temporary breakpoint 1 at 0xe960: file ./src/calamares/main.cpp, line 36.
Starting program: /usr/bin/calamares
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffe5e8) at ./src/calamares/main.cpp:36
36      {
(gdb) continue
Continuing.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[New Thread 0x7fffe7d79700 (LWP 17581)]
20:10:32 [1]: Calamares version: 3.1.4.20170916-git-master-9197873-dirty
20:10:32 [1]: Default font =====
Pixel size:    -1
Point size:    9
Point sizeF:   9
Font family:   "Sans Serif"
Metric height: 15
20:10:32 [1]: Font height: 15
20:10:32 [1]: Available languages: ("ar", "ast", "bg", "ca", "cs_CZ", "da", "de", "el", "en", "en_GB", "es_MX", "es", "eu", "fr", "he", "hr", "hu", "id", "is", "it_IT", "ja", "lt", "nl", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sv", "th", "tr_TR", "zh_CN", "zh_TW")
20:10:32 [1]: CalamaresApplication thread: 0x555555848c20
20:10:32 [1]: Using log file: "/root/.cache/Calamares/Calamares/Calamares.log"
20:10:32 [1]: Using Calamares settings file at "/etc/calamares/settings.conf"
20:10:32 [1]: Using Calamares branding file at "/etc/calamares/branding/siduction/branding.desc"
20:10:32 [1]: WARNING: the selected branding component does not ship translations.
20:10:32 [1]: Loaded branding component "siduction"
20:10:32 [1]: STARTUP: initQmlPath, initSettings, initBranding done
20:10:32 [1]: STARTUP: initModuleManager: module init started
[New Thread 0x7fffe50bb700 (LWP 17582)]
20:10:32 [1]: STARTUP: initModuleManager: all modules init done
20:10:32 [1]: STARTUP: initJobQueue done
20:10:32 [1]: Available size QSize(1688, 1018)
20:10:32 [1]:   Proposed window size: 1024 540
20:10:32 [1]: STARTUP: CalamaresWindow created; loadModules started

Thread 1 "calamares" received signal SIGSEGV, Segmentation fault.
QHash<QString, QPair<QMetaObject const*, QObject* (*)(QWidget*, QObject*)> >::findNode (this=this@entry=0x555555a2f6d0, akey=..., h=32767) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:908
908             while (*node != e && !(*node)->same_key(h, akey))
```
> backtrace
```
(gdb) bt
#0  QHash<QString, QPair<QMetaObject const*, QObject* (*)(QWidget*, QObject*)> >::findNode (this=this@entry=0x555555a2f6d0, akey=..., h=32767) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:908
#1  0x00007ffff7937c2e in QHash<QString, QPair<QMetaObject const*, QObject* (*)(QWidget*, QObject*)> >::findNode (this=this@entry=0x555555a2f6d0, akey=..., ahp=ahp@entry=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:927
#2  0x00007ffff7937f5a in QHash<QString, QPair<QMetaObject const*, QObject* (*)(QWidget*, QObject*)> >::values (this=this@entry=0x555555a2f6d0, akey=...)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:713
#3  0x00007ffff7936ffc in Calamares::PluginFactory::doRegisterPlugin (this=this@entry=0x555555900350, keyword=..., metaObject=0x7fffe4708280 <WelcomeViewStep::staticMetaObject>,
    instanceFunction=instanceFunction@entry=0x7fffe44fde80 <Calamares::PluginFactory::createInstance<WelcomeViewStep, QObject>(QWidget*, QObject*)>) at ./src/libcalamares/utils/PluginFactory.cpp:69
#4  0x00007fffe44fcee5 in Calamares::PluginFactory::registerPlugin<WelcomeViewStep> (instanceFunction=<optimized out>, keyword=..., this=0x555555900350) at ./src/libcalamares/utils/PluginFactory.h:300
#5  WelcomeViewStepFactory::WelcomeViewStepFactory (this=0x555555900350) at ./src/modules/welcome/WelcomeViewStep.cpp:28
#6  0x00007fffe45023dd in qt_plugin_instance () at ./obj-x86_64-linux-gnu/src/modules/welcome/calamares_viewmodule_welcome_autogen/EWIEGA46WW/moc_WelcomeViewStep.cpp:220
#7  0x00007ffff646cb06 in QPluginLoader::instance() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff7b99961 in Calamares::ViewModule::loadSelf (this=0x555555a2e950) at ./src/libcalamaresui/modulesystem/ViewModule.cpp:52
#9  0x00007ffff7b90688 in Calamares::ModuleManager::<lambda()>::operator()(void) const (__closure=0x555555a2e420) at ./src/libcalamaresui/modulesystem/ModuleManager.cpp:290
#10 0x00007ffff64c53e4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff64b938b in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff720446c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff720bd34 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff6489d68 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff64e189e in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff64e2061 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff2599f67 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff259a1a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff259a22c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff64e23ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff6487dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6490d24 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x0000555555562c51 in main (argc=<optimized out>, argv=<optimized out>) at ./src/calamares/main.cpp:71
```

**Comment by philmmanjaro** [comment]
What about the latest commit ca60a7f? Seems there were additional patches added for **clang**.

**Comment by agaida** [comment]
@philmmanjaro - we always use latest git unless we are in release mode, so i noted the segfault wit excatly ca60a7f - fortunately i had a working build from some days ago - so it was more or less easy to find the commit that introduce the segfault-
```
calamares (3.1.5~39~really~3.1.4-20-gec8692283-3) unstable; urgency=medium

  [ Alf Gaida ]
  * back to v3.1.4-20-gec8692283

 -- Alf Gaida <agaida@siduction.org>  Sun, 17 Sep 2017 02:31:48 +0200

calamares (3.1.5~39~really~3.1.4-20-gec8692283-2) unstable; urgency=medium

  * New snapshot: v3.1.4-21-gbe2338ff0 - broken

 -- siducer <siducer@newdev.siduction.org>  Sat, 16 Sep 2017 19:56:47 -0400

calamares (3.1.5~39~really~3.1.4-20-gec8692283-1) unstable; urgency=medium

  [ root ]
  * New snapshot: v3.1.4-20-gec8692283 works

 -- siducer <siducer@newdev.siduction.org>  Sat, 16 Sep 2017 19:53:23 -0400

calamares (3.1.5~38-gca60a7fc1-4) unstable; urgency=medium

  * New snapshot: v3.1.4-19-gd8a47bb8b works

 -- root <root@newdev.siduction.org>  Sat, 16 Sep 2017 19:36:30 -0400

calamares (3.1.5~38-gca60a7fc1-3) unstable; urgency=medium

  * New snapshot: v3.1.4-16-g2d94e8802 works

 -- root <root@newdev.siduction.org>  Sat, 16 Sep 2017 19:31:23 -0400

calamares (3.1.5~38-gca60a7fc1-2) unstable; urgency=medium

  * New snapshot: v3.1.4-21-gbe2338ff0 broken

 -- root <root@newdev.siduction.org>  Sat, 16 Sep 2017 19:21:49 -0400

calamares (3.1.5~38-gca60a7fc1-1.1) unstable; urgency=medium

  * New snapshot: v3.1.4-11-gd2964cc71 - works
  * New snapshot: v3.1.4-32-gc9f4bc0cc - broken

 -- root <root@newdev.siduction.org>  Sat, 16 Sep 2017 19:11:44 -0400

calamares (3.1.5~38-gca60a7fc1-1) unstable; urgency=medium

  * New snapshot: v3.1.4-38-gca60a7fc1
  * Removed get-snapshot, added repository.spec
  * Removed is-mounted.patch, handled upstream

 -- Alf Gaida <agaida@siduction.org>  Fri, 15 Sep 2017 23:53:45 +0200

```
